### ISSUE TITLE
mkv.tags output format?

### ISSUE THREAD

**Issue by jimlynnjulian** [Diaoul/enzyme#32]
I assumed the output of mkv.tags was a python dictionary and tried to convert to json without success. The output is not json. XML conversion failed too.
What is the output format?

**Comment by jimlynnjulian** [comment]
Hello aulemahal,
   How does that work? I used your tip, then pasted the output to a couple of json formatters/validators and got errors. I'm not that familiar with json. I also tried running the output through a json to xml converter with the same problems. I also tried json.dumps() without success. "not serializable", and other issues.
jsonlint.com
codebeautify.org/jsontoxml
A plugin for notepad++ that 'pretifies' xml worked, but the tag arrangement is strange.
I'm calling this a dead app. Moving on. Thanks for your efforts.

**Comment by jimlynnjulian** [comment]
Tried everything, but nothing worked.

**Comment by aulemahal** [comment]
This is very much a dead app, indeed.

If you find yourself as lost as I was with the python options for handling MKV, here are my two suggestions:
- Wrap tools from mkvtoolnix and process their output
- Fork my branch of enzyme : `aulemahal:attachments-and-xml`. There, I added XML serialization and a few other things. But it's been stale since 2017, and I won't maintain it, sorry.
